<?php

use Illuminate\Database\Seeder;
use App\Models\Zone;

class ZonesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $zones = [            
            ['district_id' => 2, 'name' => 'Bhadra'],
            ['district_id' => 2, 'name' => 'Padma R/A'],
            ['district_id' => 2, 'name' => 'Bosepara'],
            ['district_id' => 2, 'name' => 'Mirer Tek'],
            ['district_id' => 2, 'name' => 'Sagarpara'],
            ['district_id' => 2, 'name' => 'Tikapara'],
            ['district_id' => 2, 'name' => 'Shadhur More'],
            ['district_id' => 2, 'name' => 'Baliapukur'],
            ['district_id' => 2, 'name' => 'Ramchandrapur'],
            ['district_id' => 2, 'name' => 'Boalia Thana'],
            ['district_id' => 2, 'name' => 'Hatemkha'],
            ['district_id' => 2, 'name' => 'Hazrapukur'],
            ['district_id' => 2, 'name' => 'Rajshahi Board'],
            ['district_id' => 2, 'name' => 'Kazihata'],
            ['district_id' => 2, 'name' => 'Hossainiganj'],
            ['district_id' => 2, 'name' => 'Rajshahi University'],
            ['district_id' => 2, 'name' => 'RUET'],
            ['district_id' => 2, 'name' => 'Rajshahi Medical'],
            ['district_id' => 2, 'name' => 'Uposhohor'],
            ['district_id' => 2, 'name' => 'Rajshahi New Market'],
            ['district_id' => 2, 'name' => 'Rajshahi Court'],
            ['district_id' => 2, 'name' => 'Rajshahi GPO'],
            ['district_id' => 2, 'name' => 'Shaheb Bazar'],
            ['district_id' => 2, 'name' => 'Seroil'],
            ['district_id' => 2, 'name' => 'Chhoto Bongram'],
            ['district_id' => 2, 'name' => 'Rajshahi Stadium'],
            ['district_id' => 2, 'name' => 'Salbagan'],
            ['district_id' => 2, 'name' => 'Kadirganj'],
            ['district_id' => 2, 'name' => 'Vatapara'],
            ['district_id' => 2, 'name' => 'Laxmipur'],
            ['district_id' => 2, 'name' => 'Kazla'],
            ['district_id' => 2, 'name' => 'Binodpur'],     
            ['district_id' => 1, 'name' => 'Adabor'],
            ['district_id' => 1, 'name' => 'Aftabnagar'],
            ['district_id' => 1, 'name' => 'Agargaon'],
            ['district_id' => 1, 'name' => 'Azimpur'],
            ['district_id' => 1, 'name' => 'Babubazar'],
            ['district_id' => 1, 'name' => 'Badda'],
            ['district_id' => 1, 'name' => 'Banani'],
            ['district_id' => 1, 'name' => 'Bangshal'],
            ['district_id' => 1, 'name' => 'Baridhara'],
            ['district_id' => 1, 'name' => 'Baridhara J Block'],
            ['district_id' => 1, 'name' => 'Basundhara RA'],
            ['district_id' => 1, 'name' => 'Bawnia'],
            ['district_id' => 1, 'name' => 'Dakshin Khan'],
            ['district_id' => 1, 'name' => 'Dayaganj'],
            ['district_id' => 1, 'name' => 'Dhaka University'],
            ['district_id' => 1, 'name' => 'Dhalpur'],
            ['district_id' => 1, 'name' => 'Dhanmondi'],
            ['district_id' => 1, 'name' => 'Dholaipar'],
            ['district_id' => 1, 'name' => 'DOHS Banani'],
            ['district_id' => 1, 'name' => 'DOHS Baridhara'],
            ['district_id' => 1, 'name' => 'DOHS Mirpur'],
            ['district_id' => 1, 'name' => 'DOHS Mohakhali'],
            ['district_id' => 1, 'name' => 'Eskaton'],
            ['district_id' => 1, 'name' => 'Faridabad'],
            ['district_id' => 1, 'name' => 'Farmgate'],
            ['district_id' => 1, 'name' => 'Gabtoli'],
            ['district_id' => 1, 'name' => 'Gandaria'],
            ['district_id' => 1, 'name' => 'Gulshan'],
            ['district_id' => 1, 'name' => 'Indira Road'],
            ['district_id' => 1, 'name' => 'Jatrabari'],
            ['district_id' => 1, 'name' => 'Jurain'],
            ['district_id' => 1, 'name' => 'Kakrail'],
            ['district_id' => 1, 'name' => 'Kalabagan'],
            ['district_id' => 1, 'name' => 'Kallyanpur'],
            ['district_id' => 1, 'name' => 'Kalshi'],
            ['district_id' => 1, 'name' => 'Khilgaon'],
            ['district_id' => 1, 'name' => 'Khilkhet'],
            ['district_id' => 1, 'name' => 'Kotwali'],
            ['district_id' => 1, 'name' => 'Lalbagh'],
            ['district_id' => 1, 'name' => 'Lalmatia'],
            ['district_id' => 1, 'name' => 'Malibagh'],
            ['district_id' => 1, 'name' => 'Maniknagar'],
            ['district_id' => 1, 'name' => 'Matikata'],
            ['district_id' => 1, 'name' => 'Matuail'],
            ['district_id' => 1, 'name' => 'Merul Badda'],
            ['district_id' => 1, 'name' => 'Mirpur'],
            ['district_id' => 1, 'name' => 'Moghbazaar'],
            ['district_id' => 1, 'name' => 'Mohakhali'],
            ['district_id' => 1, 'name' => 'Mohammadpur'],
            ['district_id' => 1, 'name' => 'Motijheel'],
            ['district_id' => 1, 'name' => 'Mridhabari'],
            ['district_id' => 1, 'name' => 'Niketan'],
            ['district_id' => 1, 'name' => 'Nikunja'],
            ['district_id' => 1, 'name' => 'Paikpara'],
            ['district_id' => 1, 'name' => 'Pallabi'],
            ['district_id' => 1, 'name' => 'Paltan'],
            ['district_id' => 1, 'name' => 'PanthaPath'],
            ['district_id' => 1, 'name' => 'Pink City'],
            ['district_id' => 1, 'name' => 'Ramna'],
            ['district_id' => 1, 'name' => 'Rampura'],
            ['district_id' => 1, 'name' => 'Rayerbagh'],
            ['district_id' => 1, 'name' => 'Sadarghat'],
            ['district_id' => 1, 'name' => 'Shaymoli'],
            ['district_id' => 1, 'name' => 'Shonir akra'],
            ['district_id' => 1, 'name' => 'Sutrapur'],
            ['district_id' => 1, 'name' => 'Tejgaon'],
            ['district_id' => 1, 'name' => 'Tongi'],
            ['district_id' => 1, 'name' => 'Uttar Khan'],
            ['district_id' => 1, 'name' => 'Uttara'],
            ['district_id' => 1, 'name' => 'Vatara'],
            ['district_id' => 1, 'name' => 'Wari'],
        ];

        foreach ($zones as $zone) {
            Zone::create($zone);
        }
    }
}
